/**
 * TDS Renamer — naming-policy v1.1 기반 자동 리네이밍
 *
 * Mode 1: renameProductDesign — 프로덕트 디자인 화면 리네이밍
 * Mode 2: renameTDSLibrary — TDS 라이브러리 컴포넌트 리네이밍 + 프로퍼티 점검
 */

import {
  BANNED_SUFFIXES,
  AUTO_GENERATED_PATTERNS,
  SPECIAL_CHARS_IN_NAMES,
  ALLOWED_ROLES,
  STRUCTURAL_LAYER_NAMES,
  KOREAN_LABEL_MAP,
  SHADCN_COMPONENTS,
} from './rules';

import {
  isTDSInstance,
  walkTree,
  getTargetNodes,
  inferContext,
  pascalToTitleCase,
  allChildrenSameType,
  hasOnlyLayoutProps,
} from './utils';

import {
  checkComponentProperties,
  checkPartNameOrder,
  PropertyIssue,
} from './property-checker';

// ============================================
// 타입
// ============================================

export interface RenameEntry {
  nodeId: string;
  before: string;
  after: string;
  reason: string;
}

export interface RenamerResult {
  mode: 'product' | 'library';
  entries: RenameEntry[];
  propertyIssues: PropertyIssue[];
  skipped: number;
  total: number;
}

// ============================================
// Mode 1: 프로덕트 디자인 리네이밍
// ============================================

export function analyzeProductDesign(): RenamerResult {
  const targets = getTargetNodes();
  const entries: RenameEntry[] = [];
  let skipped = 0;
  let total = 0;

  for (const node of walkTree(targets)) {
    total++;

    // TDS 인스턴스 내부는 skip
    if (isTDSInstance(node)) {
      skipped++;
      continue;
    }

    // 인스턴스의 자식도 skip (부모가 인스턴스면)
    if (isInsideTDSInstance(node)) {
      skipped++;
      continue;
    }

    const newName = computeProductName(node);
    if (newName && newName !== node.name) {
      entries.push({
        nodeId: node.id,
        before: node.name,
        after: newName,
        reason: getRenameReason(node.name, newName),
      });
    }
  }

  return { mode: 'product', entries, propertyIssues: [], skipped, total };
}

export function applyProductRenames(entries: RenameEntry[]): number {
  let applied = 0;
  for (const entry of entries) {
    const node = figma.getNodeById(entry.nodeId);
    if (node && 'name' in node) {
      (node as SceneNode).name = entry.after;
      applied++;
    }
  }
  return applied;
}

// ============================================
// Mode 2: TDS 라이브러리 리네이밍 + 프로퍼티 점검
// ============================================

export function analyzeTDSLibrary(): RenamerResult {
  const selection = figma.currentPage.selection;
  const entries: RenameEntry[] = [];
  const propertyIssues: PropertyIssue[] = [];
  let total = 0;

  for (const node of selection) {
    if (node.type !== 'COMPONENT' && node.type !== 'COMPONENT_SET') {
      figma.notify('COMPONENT 또는 COMPONENT_SET을 선택하세요.', { error: true });
      continue;
    }

    total++;

    // 1. Display Name 매칭
    const shadcnMatch = findShadcnMatch(node.name);
    if (shadcnMatch && shadcnMatch !== node.name) {
      entries.push({
        nodeId: node.id,
        before: node.name,
        after: shadcnMatch,
        reason: `shadcn 공식명 매칭: ${shadcnMatch}`,
      });
    }

    // 2. 프로퍼티 점검
    propertyIssues.push(...checkComponentProperties(node));

    // 3. 내부 파트명 순서 점검
    propertyIssues.push(...checkPartNameOrder(node));

    // 4. 내부 레이어 리네이밍 (COMPONENT_SET의 children)
    if ('children' in node) {
      for (const child of walkTree(node.children as SceneNode[])) {
        total++;
        // 특수문자 제거
        if (SPECIAL_CHARS_IN_NAMES.test(child.name)) {
          const cleaned = child.name.replace(SPECIAL_CHARS_IN_NAMES, '').trim();
          entries.push({
            nodeId: child.id,
            before: child.name,
            after: cleaned,
            reason: '특수문자 제거',
          });
        }
      }
    }
  }

  return { mode: 'library', entries, propertyIssues, skipped: 0, total };
}

// ============================================
// 내부 로직
// ============================================

function computeProductName(node: SceneNode): string | null {
  const name = node.name;

  // Step 1: 한글 → 영문
  const koreanMatch = KOREAN_LABEL_MAP[name.trim()];
  if (koreanMatch) return koreanMatch;

  // Step 2: 자동 생성명 추론
  if (isAutoGenerated(name)) {
    return inferName(node);
  }

  // Step 3: 금지 접미사 대체
  const bannedResult = replaceBannedSuffix(node, name);
  if (bannedResult) return bannedResult;

  // Step 4: 슬래시 → 공백
  if (name.includes('/') && node.type !== 'INSTANCE') {
    return name.replace(/\//g, ' ').replace(/\s+/g, ' ').trim();
  }

  // Step 5: PascalCase → Title Case
  const titleCased = pascalToTitleCase(name);
  if (titleCased !== name) return titleCased;

  // Step 6: 특수문자 제거
  if (SPECIAL_CHARS_IN_NAMES.test(name)) {
    return name.replace(SPECIAL_CHARS_IN_NAMES, '').trim();
  }

  return null; // 변경 불필요
}

function isAutoGenerated(name: string): boolean {
  return AUTO_GENERATED_PATTERNS.some((p) => p.test(name));
}

function inferName(node: SceneNode): string {
  const context = inferContext(node);
  const prefix = context || 'Unnamed';

  // 자식 기반 추론
  if ('children' in node) {
    const children = (node as FrameNode).children;

    // 자식 1개 → 자식 기반
    if (children.length === 1) {
      const childName = children[0].name.split(/[\s/]/)[0];
      const role = STRUCTURAL_LAYER_NAMES[childName.toLowerCase()];
      if (role) return `${prefix} ${role}`;
      return `${childName} Area`;
    }

    // 자식 n개 → 부모 컨텍스트 + 역할
    if (children.length > 1) {
      if (allChildrenSameType(node)) return `${prefix} Group`;
      return `${prefix} Content`;
    }
  }

  // 루트 레벨
  if (node.parent === figma.currentPage) {
    return `${prefix} Screen`;
  }

  // 폴백
  return `${prefix} Section`;
}

function replaceBannedSuffix(node: SceneNode, name: string): string | null {
  const words = name.split(/\s+/);

  for (const banned of BANNED_SUFFIXES) {
    const idx = words.findIndex((w) => w.toLowerCase() === banned.toLowerCase());
    if (idx === -1) continue;

    // "Container X" → 컨텍스트 추출
    const remaining = words.filter((_, i) => i !== idx).join(' ').trim();
    const context = remaining || inferContext(node) || 'Main';

    // 대체 어휘 선택
    if ('children' in node && allChildrenSameType(node)) {
      return `${context} Group`;
    }
    if (hasOnlyLayoutProps(node)) {
      return `${context} Area`;
    }
    return `${context} Content`;
  }

  return null;
}

function findShadcnMatch(name: string): string | null {
  const normalized = name.split('/')[0].trim();
  return SHADCN_COMPONENTS.find(
    (sc) => sc.toLowerCase() === normalized.toLowerCase()
      || sc.replace(/\s/g, '').toLowerCase() === normalized.replace(/\s/g, '').toLowerCase()
  ) || null;
}

function isInsideTDSInstance(node: SceneNode): boolean {
  let current = node.parent;
  while (current && current.type !== 'PAGE') {
    if (current.type === 'INSTANCE') {
      return isTDSInstance(current as InstanceNode);
    }
    current = current.parent;
  }
  return false;
}

function getRenameReason(before: string, after: string): string {
  if (isAutoGenerated(before)) return '자동 생성명 → 시맨틱 추론';
  for (const banned of BANNED_SUFFIXES) {
    if (before.toLowerCase().includes(banned.toLowerCase())) return `금지어 ${banned} → 대체`;
  }
  if (before.includes('/')) return '슬래시 → 공백 변환';
  if (before !== pascalToTitleCase(before)) return 'PascalCase → Title Case';
  if (SPECIAL_CHARS_IN_NAMES.test(before)) return '특수문자 제거';
  if (KOREAN_LABEL_MAP[before.trim()]) return '한글 → 영문';
  return '네이밍 정책 적용';
}
